SGEI/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('editais/', include('editais.urls', namespace='editais')),

    path('relatorios/', include('relatorios.urls', namespace='relatorios')),

   

    

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
      + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include

from accounts.views import create_user_arquivo, perfil, list_users

app_name='accounts'

urlpatterns = [
    path('user/arquivo/', create_user_arquivo, name='create_user_arquivo'),
    path('user/perfil/', perfil, name='perfil_user'),
    path('user/list/', list_users, name='list_user'),
]

core/urls.py
from django.urls import path
from .views import home,mylogout,index

app_name = 'core'

urlpatterns = [
    path('',home, name='home'),
    path('index/', index, name='index'),
    path('logout/', mylogout, name="mylogout"),
]

editais/urls.py
from django.urls import path, include

from .views import EditalList, edital_view_adm, InscricaolList, edital_add, edital_delete, edital_edit, \
    inscricao_view, edital_view, \
    pergunta_add, pergunta_edit, pergunta_delete, inscricao_do, inscricao_list_user, edital_list_adm, \
    inscricao_view_user, edital_list_aluno, resultado_edital, inscricao_edit, inscricao_list

app_name='editais'
urlpatterns = [

    #----------------Edital-------------------
    path('', edital_list_adm, name='edital_list'),
    path('view/edital/<int:id>', edital_view_adm, name='edital_view'),
    path('add/edital/', edital_add, name="edital_add"),
    path('edit/edital/<int:id>', edital_edit, name="edital_edit"),
    path('delete/edital/<int:id>', edital_delete, name='edital_delete'),

    path('alunos/edital/list/', edital_list_aluno, name='edital_list_inscri'),
    path('alunos/edital/<int:id>', edital_view, name='edital_view_inscri'),


    path('resultado/edital/<int:id>', resultado_edital, name='resultado_edital'),




    #----------------Pergunta-------------------
    path('add/pergunta/<int:id_edital>', pergunta_add, name="pergunta_add"),
    path('edit/pergunta/<int:id>', pergunta_edit, name="pergunta_edit"),
    path('delete/pergunta/<int:id>', pergunta_delete, name='pergunta_delete'),


    #----------------Incrições-------------------
    path('inscricao/', inscricao_list, name='inscricao_list'),
    path('view/inscricao/<int:id>', inscricao_view, name='inscricao_view'),
    path('alunos/inscricao/<int:id>', inscricao_view_user, name='inscricao_view_user'),
    path('alunos/inscricao/', inscricao_list_user, name='inscricao_list_user'),


    path('inscricao/do/<int:id_edital>', inscricao_do, name='inscricao_do'),
    path('inscricao/edit/<int:id>', inscricao_edit, name='inscricao_edit'),
]

templates/includes/sidenav.html
{% if request.user.is_staff %}

<ul id="slide-out" class="sidenav sidenav-fixed green darken-4 menu">

    <li>

        <h5 class="white-text center-align "><b>SGEI</b> <sup>IFNMG</sup></h5>

        <div class="user-view">


            {% if user.is_authenticated %} {% if user.foto %}

            <a href="#user"><img class="circle" src="/media/{{user.foto}} "></a>

            {% else %}

            <a href="#user "><img class="circle " src="/static/img/user.png "></a>

            {% endif %}

            <a href="# " class="z-depth-0 dropdown-trigger white-text " data-target="menu-sair "><span class="white-text name "> Olá, {{user.username}}<i class="material-icons right ">arrow_drop_down</i></span></a>
            <a href="#email "><span class="white-text email ">{{user.first_name}}</span></a>

            <a href="#email ">
                <span class="white-text email ">{{user.email}}</span> </a> {% else %}

            <a href="#user " style="align-items: center; "><img class="circle " src="/static/img/user.png "></a>
            <a href="#name "><span class="white-text name ">SGEI</span></a>
            <a href="{% url 'account_login' %} "><span class="white-text email ">Entrar</span></a> {% endif %}

        </div>
    </li>


    <li class="nav-link ">
        <a href="{% url 'core:index'%} " class="z-depth-0 white-text ">
            <i class="material-icons white-text ">home</i> Inicio
        </a>
    </li>

    <li class="nav-link ">
        <a href="# " class="dropdown-trigger white-text " data-target="menuedital-mobile ">
            <i class="material-icons white-text ">content_paste</i> Editais
        </a>
    </li>
    <li class="nav-link ">
        <a href="# " class="dropdown-trigger white-text " data-target="menuinscricao-mobile ">
            <i class="material-icons white-text ">library_books</i> Inscrições
        </a>
    </li>
    <li class="nav-link ">
        <a href="# " class="dropdown-trigger white-text " data-target="menuusuario-mobile ">
            <i class="material-icons white-text ">supervisor_account</i> Usuarios
        </a>
    </li>

</ul>

<!--     menu -->

<ul id="menu-sair " class="dropdown-content menu-dropdown ">
    <li><a href="{%url 'accounts:perfil_user'%} ">´Perfil</a></li>
    <li><a href="{% url 'core:mylogout'%} ">Sair</a></li>

</ul>

<ul id="menuinscricao-mobile " class="dropdown-content menu-dropdown ">

    <li><a href="{% url 'editais:inscricao_list'%} ">Listar inscrições</a></li>


</ul>
<ul id="menuusuario-mobile " class=" dropdown-content menu-dropdown ">
    <li><a href=" {% url 'accounts:create_user_arquivo' %}">Adicionar Usuario</a></li>
    <li><a href=" {% url 'accounts:list_user' %} ">Listar Usuarios</a></li>

</ul>

<ul id="menuedital-mobile " class="dropdown-content menu-dropdown ">
    <li><a href="{% url 'editais:edital_add' %} ">Adicionar Edital</a></li>
    <li><a href="{% url 'editais:edital_list'%} ">Listar Editais</a></li>


</ul>
<br>
<div class="container"> <a href="#" data-target="slide-out" class="sidenav-trigger hide-on-large-only "><i class="material-icons">menu</i></a> </div>

{% else %}

<ul id="slide-out" class="sidenav sidenav-fixed green darken-4 menu">

    <li>

        <h5 class="white-text center-align "><b>SGEI</b> <sup>IFNMG</sup></h5>

        <div class="user-view">


            {% if user.is_authenticated %} {% if user.foto %}

            <a href="#user"><img class="circle" src="/media/{{user.foto}} "></a>

            {% else %}

            <a href="#user "><img class="circle " src="/static/img/user.png "></a>

            {% endif %}

            <a href="#" class="z-depth-0 dropdown-trigger white-text " data-target="menusair-Usuario "><span class="white-text name "> Olá, {{user.username}}<i class="material-icons right ">arrow_drop_down</i></span></a>


            <a href="#email">
                <span class="white-text email ">{{user.email}}</span> </a> {% else %}

            <a href="#user " style="align-items: center; "><img class="circle " src="/static/img/user.png "></a>
            <a href="#name "><span class="white-text name ">SGEI</span></a>
            <a href="{% url 'account_login' %} "><span class="white-text email ">Entrar</span></a> {% endif %}

        </div>
    </li>
    <li class="nav-link ">
        <a href="{% url 'core:index'%} " class="z-depth-0 white-text ">
            <i class="material-icons white-text ">home</i> Inicio
        </a>
    </li>

    <li class="nav-link ">
        <a href="# " class="dropdown-trigger white-text " data-target="menuedital-Usuario ">
            <i class="material-icons white-text ">content_paste</i> Editais
        </a>
    </li>
    <li class="nav-link ">
        <a href="# " class="dropdown-trigger white-text " data-target="menuinscricao-Usuario ">
            <i class="material-icons white-text ">library_books</i> Inscrições
        </a>
    </li>

</ul>


<br>
<div class="container"> <a href="#" data-target="slide-out" class="sidenav-trigger hide-on-large-only "><i class="material-icons">menu</i></a> </div>


<ul id="menuinscricao-Usuario " class="dropdown-content menu-dropdown ">

    <li><a href="{% url 'editais:inscricao_list_user' %} ">Listar inscrições</a></li>

</ul>

<ul id="menuedital-Usuario " class="dropdown-content menu-dropdown ">

    <li><a href="{% url 'editais:edital_list_inscri'%} ">Listar Editais</a></li>

</ul>
<ul id="menusair-Usuario " class="dropdown-content menu-dropdown ">
    <li><a href="{%url 'accounts:perfil_user'%}">Perfil</a></li>
    <li><a href="{% url 'core:mylogout'%} ">Sair</a></li>

</ul>

{%endif%}