SGEI/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('editais/', include('editais.urls', namespace='editais')),

    path('relatorios/', include('relatorios.urls', namespace='relatorios')),

   

    

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
      + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editais/urls.py
from django.urls import path, include

from .views import EditalList, edital_view_adm, InscricaolList, edital_add, edital_delete, edital_edit, \
    inscricao_view, edital_view, \
    pergunta_add, pergunta_edit, pergunta_delete, inscricao_do, inscricao_list_user, edital_list_adm, \
    inscricao_view_user, edital_list_aluno, resultado_edital, inscricao_edit, inscricao_list

app_name='editais'
urlpatterns = [

    #----------------Edital-------------------
    path('', edital_list_adm, name='edital_list'),
    path('view/edital/<int:id>', edital_view_adm, name='edital_view'),
    path('add/edital/', edital_add, name="edital_add"),
    path('edit/edital/<int:id>', edital_edit, name="edital_edit"),
    path('delete/edital/<int:id>', edital_delete, name='edital_delete'),

    path('alunos/edital/list/', edital_list_aluno, name='edital_list_inscri'),
    path('alunos/edital/<int:id>', edital_view, name='edital_view_inscri'),


    path('resultado/edital/<int:id>', resultado_edital, name='resultado_edital'),




    #----------------Pergunta-------------------
    path('add/pergunta/<int:id_edital>', pergunta_add, name="pergunta_add"),
    path('edit/pergunta/<int:id>', pergunta_edit, name="pergunta_edit"),
    path('delete/pergunta/<int:id>', pergunta_delete, name='pergunta_delete'),


    #----------------Incrições-------------------
    path('inscricao/', inscricao_list, name='inscricao_list'),
    path('view/inscricao/<int:id>', inscricao_view, name='inscricao_view'),
    path('alunos/inscricao/<int:id>', inscricao_view_user, name='inscricao_view_user'),
    path('alunos/inscricao/', inscricao_list_user, name='inscricao_list_user'),


    path('inscricao/do/<int:id_edital>', inscricao_do, name='inscricao_do'),
    path('inscricao/edit/<int:id>', inscricao_edit, name='inscricao_edit'),
]

relatorios/urls.py
from django.urls import path, include
from .views import relatorioedital, pdf_inscricaoDetelhada

app_name='relatorios'
urlpatterns = [
    
    path('pdf/edital/<int:id>', relatorioedital, name='relatorioedital'),
    path('view/inscriçãod/pdf/<int:id>',  pdf_inscricaoDetelhada, name='inscricaodetalhada'),
   

    

]

editais/models.py
from django.db import models
from accounts.models import User


class Edital(models.Model):

    STATUS_CHOICE = (
        ('ab', 'Aberto'),
        ('em', 'Em analise'),
        ('fn', 'Finalizado')
    )

    titulo = models.CharField(max_length=100)
    descricao = models.TextField()
    status = models.CharField(max_length=2, choices=STATUS_CHOICE, default='ab')
    banner = models.ImageField(upload_to='editais/banner', null=True, blank=True)
    arquivo = models.FileField(upload_to='editais/pdf', null=True, blank=True)

    # ---- Campos para controle de datas de criação e edição ----
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name_plural = "Edital"
        verbose_name = "Editais"

class Pergunta(models.Model):
    edital = models.ForeignKey(Edital, on_delete=models.CASCADE)
    descricao = models.TextField()
    is_aberta = models.BooleanField(default=False, null=True)
    has_arquivo = models.BooleanField(default=False, null=True)

    # ---- Campos para controle de datas de criação e edição ----
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name_plural = "Pergunta"
        verbose_name = "Perguntas"

class Alternativa(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    descricao = models.TextField()
    peso = models.IntegerField(default=0)
    # ---- Campos para controle de datas de criação e edição ----
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.descricao)

    class Meta:
        verbose_name_plural = "Alternativa"
        verbose_name = "Alternativas"

class Inscricao(models.Model):

    STATUS_CHOICE = (
        ('df', 'Defirido'),
        ('in', 'Indefirido'),
        ('an', 'Em Analise'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    edital = models.ForeignKey(Edital, on_delete=models.CASCADE)
    status = models.CharField(max_length=2, choices=STATUS_CHOICE, default='an')
    nivel_vul = models.IntegerField(default=0)

    # ---- Campos para controle de datas de criação e edição ----
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def nivel(self):
        respostas = list(self.resposta_set.all())

        pontos = 0

        for resp in respostas:

            if resp.alternativa != None  and \
                    resp.alternativa != None:

                pontos += resp.alternativa.peso
        self.nivel_vul = pontos
        self.save()
        return pontos



    def __str__(self):
        return "Aluno " +self.user.first_name + " Numerode inscrição " + str(self.id)

    class Meta:
        verbose_name_plural = "Inscrição"
        verbose_name = "Inscrições"
        ordering = ["-nivel_vul",]


class Resposta(models.Model):
    inscricao = models.ForeignKey(Inscricao, on_delete=models.CASCADE)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    alternativa = models.ForeignKey(Alternativa, on_delete=models.CASCADE, null=True, blank=True)
    arquivo = models.FileField(upload_to='inscricoes', null=True, blank=True)
    resposta_aberta = models.TextField(null=True, blank=True)

    # ---- Campos para controle de datas de criação e edição ----
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name_plural = "Resposta"
        verbose_name = "Respostas"

editais/forms.py
from django import forms
from material.base import Layout, Fieldset, Row

from .models import Pergunta, Edital, Alternativa, Resposta, Inscricao




class PerguntaForm(forms.ModelForm):
    is_aberta = forms.BooleanField(required=False, label='Esta pergunta é aberta')
    has_arquivo = forms.BooleanField(required=False, label='Esta pergunta requer arquivos')

    class Meta:
        model = Pergunta
        fields = ('descricao','is_aberta','has_arquivo')

    layout = Layout('descricao',
                    Row('is_aberta','has_arquivo')
                    )



class AlternativaForm(forms.ModelForm):
    class Meta:
        model = Alternativa
        fields = '__all__'

class RespostaForm(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = '__all__'



class EditalForm(forms.ModelForm):
    class Meta:
        model = Edital
        fields = '__all__'



class InscricaoForm(forms.ModelForm):
    class Meta:
        model = Inscricao
        fields = '__all__'



class IncricaoFormAv(forms.ModelForm):
    class Meta:
        model = Inscricao
        fields = ('status',)

editais/views.py
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView, ListView

from django.core.files.storage import FileSystemStorage

from .forms import EditalForm, PerguntaForm, AlternativaForm, IncricaoFormAv
from .models import Edital, Inscricao, Pergunta, Alternativa, Resposta


#Edital área

# administração

@login_required
def edital_list_adm(request):
    context = {}
    editais_abertos = Edital.objects.filter(status='ab')
    editais_analise = Edital.objects.filter(status='em')
    editais_fechados = Edital.objects.filter(status='fn')


    context['editais_abertos'] = editais_abertos
    context['editais_analise'] = editais_analise
    context['editais_fechados'] = editais_fechados


    return render(request,'edital/list_edital.html', context)

@login_required
def edital_view_adm(request, id):
    context = {}
    edital= get_object_or_404(Edital, pk=id)
    perguntas = edital.pergunta_set.all()
    context['edital'] = edital
    context['perguntas'] = perguntas
    return render(request,'edital/view_edital.html',context)

@login_required
def edital_add(request):
    edital = Edital()
    context = {}

    if request.method == 'POST':
        form = EditalForm(request.POST or None, request.FILES or None, instance=edital, prefix='edital')

        if form.is_valid():
            form = form.save(commit=False)

            edital = form.save()

            return redirect('editais:edital_list')
        else:
            context['form'] = EditalForm(request.POST or None, request.FILES or None, instance=edital, prefix='edital')


    else:
        context['form'] = EditalForm( instance=edital, prefix='edital')



    return render(request,'edital/add_edital.html', context)


@login_required
def  edital_edit(request, id):
    context = {}
    edital = get_object_or_404(Edital, pk=id)

    if request.method == 'POST':
        form = EditalForm(request.POST or None, request.FILES or None, instance=edital, prefix='edital')



        if form.is_valid():
            form = form.save(commit=False)
            form.save()


            return redirect('editais:edital_view', id=edital.id)
        else:
            context['form'] = EditalForm(request.POST or None, request.FILES or None, instance=edital, prefix='edital')


    else:
        context['form'] = EditalForm(instance=edital, prefix='edital')



    return render(request,'edital/add_edital.html', context)


@login_required
def edital_delete(request, id):
    edital = get_object_or_404(Edital, pk=id)
    edital.delete()

    return redirect('editais:edital_list')


###Alunos
class EditalList(ListView):
    template_name = 'edital/list_edital_inscri.html'
    model = Edital



def edital_list_aluno(request):
    context = {}
    editais_abertos = Edital.objects.filter(status='ab')
    editais_analise = Edital.objects.filter(status='em')
    editais_fechados = Edital.objects.filter(status='fn')

    context['editais_abertos'] = editais_abertos
    context['editais_analise'] = editais_analise
    context['editais_fechados'] = editais_fechados

    return render(request, 'edital/list_edital_inscri.html', context)


def edital_view(request, id):
    context = {}
    edital= get_object_or_404(Edital, pk=id)

    if request.user.is_anonymous == False:
        user = request.user
        inscricao = Inscricao.objects.filter(user=user,edital=edital)

        context['situacao'] = False

        if inscricao:
            context['situacao'] = True


    context['edital'] = edital
    return render(request,'edital/view_edital_inscri.html',context)



def resultado_edital(request,id):
    context = {}
    edital = get_object_or_404(Edital, pk=id)
    aprovados = Inscricao.objects.filter(edital=edital, status='df')
    reprovados = Inscricao.objects.filter(edital=edital, status='in')


    context['edital'] = edital
    context['aprovados'] = aprovados
    context['reprovados'] = reprovados
    return render(request,'edital/resultado_edital.html',context)







#------------------- Perguntas ---------------------
@login_required
def pergunta_add(request, id_edital):
    form_alternativa_factory = inlineformset_factory(Pergunta, Alternativa, form=AlternativaForm)

    edital = get_object_or_404(Edital, pk=id_edital)
    pergunta = Pergunta()
    pergunta.edital = edital
    context = {}

    if request.method == 'POST':

        form = PerguntaForm(request.POST or None, request.FILES or None, instance=pergunta, prefix='pergunta')
        alternativa_form = form_alternativa_factory(request.POST or None, request.FILES or None, instance=pergunta,
                                                    prefix='alternativa')


        if form.is_valid() and alternativa_form.is_valid():
            form = form.save(commit=False)
            form.save()
            alternativa_form.save()
            return redirect('editais:edital_view',id =edital.id)
        else:
            context['edital'] = edital
            context['form'] = PerguntaForm(request.POST or None, request.FILES or None, instance=pergunta,
                                           prefix='pergunta')
            context['form_alternativa'] = form_alternativa_factory(request.POST or None, request.FILES or None,
                                                                   instance=pergunta, prefix='alternativa')

    else:
        context['edital'] = edital
        context['form'] = PerguntaForm(instance=pergunta, prefix='pergunta')
        context['form_alternativa'] = form_alternativa_factory(instance=pergunta, prefix='alternativa')

    return render(request, 'pergunta/add_pergunta.html', context)

@login_required
def pergunta_edit(request, id):
    form_alternativa_factory = inlineformset_factory(Pergunta, Alternativa, form=AlternativaForm)
    pergunta = get_object_or_404(Pergunta, pk=id)
    edital = pergunta.edital

    context = {}

    if request.method == 'POST':

        form = PerguntaForm(request.POST or None, request.FILES or None, instance=pergunta, prefix='pergunta')
        alternativa_form = form_alternativa_factory(request.POST or None, request.FILES or None, instance=pergunta,
                                                    prefix='alternativa')


        if form.is_valid() and alternativa_form.is_valid():
            form = form.save(commit=False)
            form.save()
            alternativa_form.save()
            return redirect('editais:edital_view',id =edital.id)
        else:
            context['edital'] = edital
            context['form'] = PerguntaForm(request.POST or None, request.FILES or None, instance=pergunta,
                                           prefix='pergunta')
            context['form_alternativa'] = form_alternativa_factory(request.POST or None, request.FILES or None,
                                                                   instance=pergunta, prefix='alternativa')

    else:
        context['edital'] = edital
        context['form'] = PerguntaForm(instance=pergunta, prefix='pergunta')
        context['form_alternativa'] = form_alternativa_factory(instance=pergunta, prefix='alternativa')

    return render(request, 'pergunta/edit_pergunta.html', context)

@login_required
def pergunta_delete(request, id):
    pergunta = get_object_or_404(Pergunta, pk=id)
    edital = pergunta.edital
    pergunta.delete()

    return redirect('editais:edital_view',id =edital.id)





#Inscrição área

class InscricaolList(ListView):
    template_name = 'inscricao/list_inscricao.html'
    model = Inscricao
@login_required
def inscricao_list(request):
    context={}
    editais = Edital.objects.all()



    search = request.GET.get('search')
    status = request.GET.get('status')
    id_edital = request.GET.get('edital')



    if id_edital:
        edital = get_object_or_404(Edital, pk=id_edital)
        if status:
            inscricao_list = Inscricao.objects.filter(status=status, edital=edital)
        else:
            inscricao_list = Inscricao.objects.filter(edital=edital)
    else:
        if status:
            inscricao_list = Inscricao.objects.filter(status=status)
        else:
            inscricao_list = Inscricao.objects.all()


    context['inscricao_list'] = inscricao_list
    context['editais'] = editais

    return render(request, 'inscricao/list_inscricao.html',context)


@login_required
def inscricao_list_user(request):
    context ={}
    incricoes = Inscricao.objects.filter(user=request.user)


    context['incricoes'] = incricoes

    return render(request, 'inscricao/user_list_inscricoes.html',context)




@login_required
def inscricao_view(request, id):
    context = {}
    inscricao= get_object_or_404(Inscricao, pk=id)


    if request.method == 'POST':
        form = IncricaoFormAv(request.POST or None, instance=inscricao)

        if form.is_valid():
            form.save()
            return redirect('editais:inscricao_list')

    else:
        form = IncricaoFormAv(request.POST or None, instance=inscricao)

    context['inscricao'] = inscricao
    context['form'] = form

    return render(request,'inscricao/view_inscricao.html',context)

@login_required
def inscricao_view_user(request, id):
    context = {}
    inscricao= get_object_or_404(Inscricao, pk=id)

    context['inscricao'] = inscricao

    return render(request,'inscricao/view_inscricao_user.html',context)


@login_required
def inscricao_do(request,id_edital):
    context = {}
    respostas = {}
    edital = get_object_or_404(Edital, pk=id_edital)

    user = request.user
    test = Inscricao.objects.filter(user=user, edital=edital)

    if test:
        return redirect('editais:inscricao_list_user')



    context['edital'] = edital
    inscricao = Inscricao()
    inscricao.edital = edital
    inscricao.user = request.user
    if(request.method == 'POST'):
        fs = FileSystemStorage()

        inscricao.save()

editais/templates/inscricao/do_inscricao.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}

{% block title %} Incrição {% endblock %}

{% block content %}
<div class="espacamento">
    <div class="card">
        <span class="card-title">Nova Inscrição</span>

        <div class="card-content">
            <form method="post" enctype="multipart/form-data" >
                {%csrf_token%}
                <div class="input-field col s12 " >
                    <input id="edital_titulo" type="text" name="edital_titulo" value="{{edital.titulo}}" readonly>
                    <label for="edital_titulo">Edital</label>
                </div>

                {%for pergunta in edital.pergunta_set.all%}
                <div class="input-field col s12 " >

                {%if pergunta.is_aberta == True%}
                    <input type="text" id="pergunta-{{pergunta.id}}" name="pergunta-{{pergunta.id}}" required>
                    <label for="pergunta-{{pergunta.id}}">{{pergunta.descricao}}</label>

                {%elif pergunta.has_arquivo == True%}

                    <div class="file-field input-field">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" id="arquivo-{{pergunta.id}}" name="arquivo-{{pergunta.id}}" required>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>


                {%else%}
                    <select name="pergunta-{{pergunta.id}}" required>
                        <option value="" disabled selected>Escolha uma Opção</option>
                        {%for alternativa in pergunta.alternativa_set.all%}
                            <option value="{{alternativa.id}}">{{alternativa.descricao}}</option>
                        {%endfor%}
                    </select>
                    <label>{{pergunta.descricao}}</label>

                {%endif%}





                </div>
                {%endfor%}


                <a href="#" class="btn btn-deletar ">Cancelar</a>
                <button type="submit" class="btn btn-salvar " >Salvar</button>


            </form>
        </div>

    </div>
</div>


{% endblock %}

editais/templates/inscricao/edit_inscricao.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}

{% block title %} Inscrição {% endblock %}

{% block content %}
<div class="espacamento">
    <div class="card">
        <span class="card-title">Editar Inscrição</span>

        <div class="card-content">

            <form method="post" enctype="multipart/form-data" >
                {%csrf_token%}
                <div class="input-field col s12 " >
                    <input id="edital_titulo" type="text" name="edital_titulo" value="{{inscricao.edital.titulo}}" readonly>
                    <label for="edital_titulo">Edital</label>
                </div>

                {% for resp in inscricao.resposta_set.all%}
                <div class="input-field col s12 " >

                    {%if resp.pergunta.is_aberta == True%}
                    <input type="text" id="pergunta-{{resp.pergunta.id}}" name="pergunta-{{resp.pergunta.id}}" value="{{resp.resposta_aberta}}" required>
                    <label for="pergunta-{{resp.pergunta.id}}">{{pergunta.descricao}}</label>

                    {%elif resp.pergunta.has_arquivo == True%}

                    <div class="file-field input-field">
                        <div class="btn">
                            <span>File</span>
                            <input type="file" id="arquivo-{{resp.pergunta.id}}" name="arquivo-{{resp.pergunta.id}}" value="{{MEDIA_URL}}{{ resp.arquivo}}" >
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>

                    {%else%}
                    <select name="pergunta-{{resp.pergunta.id}}" required>
                        <option value="" disabled selected>Escolha uma Opção</option>
                        {%for alternativa in resp.pergunta.alternativa_set.all%}

                            {% if alternativa.id == resp.alternativa.id %}
                                <option value="{{alternativa.id}}" selected>{{alternativa.descricao}}</option>
                            {%else%}
                                <option value="{{alternativa.id}}">{{alternativa.descricao}}</option>
                            {%endif%}
                        {%endfor%}
                    </select>
                    <label>{{pergunta.descricao}}</label>

                {%endif%}



                </div>
                {%endfor%}
                <a href="#" class="btn btn-deletar ">Cancelar</a>
                <button type="submit" class="btn btn-salvar " >Salvar</button>


            </form>
        </div>

    </div>
</div>


{% endblock %}

editais/templates/inscricao/list_inscricao.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}

{% block title %} Inscrições {% endblock %}

{% block content %}
<div class="espacamento">
    <div class="row">
        <div class="row">
            <div class="row">
                <span>Filtrar por:</span>
            </div>

            <div class="col s12 m4">
                <label for="edital">Edital</label>
                <select name="edital" id="edital" class="form-control">
                    <option value="">Escolha uma opção...</option>
                    {% for edital in editais %}
                        <option value="{{edital.id}}">{{edital.titulo}}</option>
                    {% endfor %}
                </select>
            </div>





            <div class="col s12 m4">
                <label for="status">Status</label>
                <select name="status" id="status" class="form-control">
                    <option value="">Escolha uma opção...</option>
                    <option value="df">Inscrições deferidas</option>
                    <option value="in">Inscrições indeferidas </option>
                    <option value="an">Inscrições em Analise </option>
                </select>
            </div>

            <a href="{% url 'editais:inscricao_list'%}" class="btn">Limpar</a>
        </div>




        <table class="striped responsive-table" >
            <thead>
              <tr>

                  <th>Aluno</th>
                  <th>Edital</th>
                  <th>Situação</th>
                  <th>Pontos</th>
                  <th>Opções</th>
              </tr>
            </thead>
            <tbody>
            {%for inscricao in inscricao_list%}
                 <tr>

                     <td>{{inscricao.user.first_name}}</td>
                     <td>{{inscricao.edital.titulo}}</td>
                     {%if inscricao.status == "an"%}
                        <td class = " yellow accent-2">{{inscricao.get_status_display}}</td>
                     {%endif%}
                     {%if inscricao.status == "df"%}
                        <td class=" teal lighten-1">{{inscricao.get_status_display}}</td>
                     {%endif%}
                     {%if inscricao.status == "in"%}
                        <td class = " red darken-3">{{inscricao.get_status_display}}</td>
                     {%endif%}
                     <td>{{inscricao.nivel}}</td>
                    <td><a href="{% url 'editais:inscricao_view' inscricao.id %}" class="blue-text"> Avaliar </a></td>
                  </tr>
            {%endfor%}
            </tbody>
        </table>

    </div>
</div>

{% endblock %}


{% block scripts %}
$( document ).ready(function() {

    var baseUrl   = "/editais/inscricao/";
    var searchBtn = $('#search-btn');
    var searchForm = $('#search-form');
    var status     = $('#status');
    var edital     = $('#edital');


    $(searchBtn).on('click', function() {
        searchForm.submit();
    });

    $(status).change(function() {
        var status = $(this).val();
        window.location.href = baseUrl + '?status=' + status;
    });

    $(edital).change(function() {
        var edital = $(this).val();
        window.location.href = baseUrl + '?edital=' + edital;
    });

});




{% endblock %}

editais/templates/inscricao/user_list_inscricoes.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}

{% block title %} Inscrições {% endblock %}

{% block content %}
<div class="espacamento">
    <div class="card-content">
        <h4>Suas inscrições</h4> <br>
        <div class="row">
            <h6>Editais abertos</h6>
            <ul class="collapsible">
                {%for insc in incricoes%}
                    {% if insc.edital.status == "ab"%}
                    <li>
                        <div class="collapsible-header"><i class="material-icons">format_list_bulleted</i>{{insc.edital}}</div>

                        <div class="collapsible-body">
                            <p><span>Edital: {{insc.edital}}</span></p>
                            <p><span class="">Situação: {{insc.get_status_display}}</span></p>
                            <a href="{% url 'editais:inscricao_view_user' insc.id %}" class="btn right">Mais Detelhes</a>
                        </div>
                    </li>
                    {%endif%}
                {%endfor%}
            </ul>

            <br><br><br>
            <h6>Editais Em Analise</h6>
            <ul class="collapsible">
                {%for insc in incricoes%}
                    {% if insc.edital.status == "em"%}
                    <li>
                        <div class="collapsible-header"><i class="material-icons">format_list_bulleted</i>{{insc.edital}}</div>

                        <div class="collapsible-body">
                            <p><span>Edital: {{insc.edital}}</span></p>
                            <p><span class="">Situação: {{insc.get_status_display}}</span></p>
                            <a href="{% url 'editais:inscricao_view_user' insc.id %}" class="btn right">Mais Detelhes</a>
                        </div>
                    </li>
                    {%endif%}
                {%endfor%}
            </ul>

            <br><br><br>
            <h6>Editais Fechados</h6>
            <ul class="collapsible">
                {%for insc in incricoes%}
                    {% if insc.edital.status == "fn"%}
                    <li>
                        <div class="collapsible-header"><i class="material-icons">format_list_bulleted</i>{{insc.edital}}</div>

                        <div class="collapsible-body">
                            <p><span>Edital: {{insc.edital}}</span></p>
                            <p><span class="">Situação: {{insc.get_status_display}}</span></p>
                            <a href="{% url 'editais:inscricao_view_user' insc.id %}" class="btn right">Mais Detelhes</a>
                        </div>
                    </li>
                    {%endif%}
                {%endfor%}
            </ul>



        </div>
    </div>
</div>
{% endblock %}

editais/templates/inscricao/view_inscricao_user.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}

{% block title %} Inscrição {% endblock %}

{% block content %}
<div class="espacamento">
    <div class="row">

        <table>
            <thead>
                <tr>
                    <th colspan="3">Edital: {{inscricao.edital}}</th>
                    <th colspan="2">Situação: {{inscricao.get_status_display}}</th>

                </tr>
                <tr>
                    <th colspan="5">Nome: {{inscricao.user.first_name}} {{inscricao.user.last_name}}</th>
                </tr>

                <tr>
                    <th colspan="3">Pergunta</th>
                    <th colspan="2">Resposta</th>
                </tr>
        </thead>
        <tbody>
        {%for resp in inscricao.resposta_set.all%}
            <tr>
                <td colspan="3">{{resp.pergunta}}</td>
                {%if resp.pergunta.is_aberta%}
                    <td colspan="2">{{resp.resposta_aberta}}</td>
                {%elif resp.pergunta.has_arquivo %}
                    <td colspan="2">
                        <a href="/media/{{resp.arquivo }} " target='_blank'>Arquivo</a>

                    </td>
                {%else%}
                    <td colspan="2">{{resp.alternativa}}</td>
                {%endif%}
            </tr>
        {% endfor %}
        </tbody>

        </table>

        {%if inscricao.edital.status == "ab"%}
            <a href="{% url 'editais:inscricao_edit' inscricao.id%}" class="btn">Editar</a>
        {%elif inscricao.edital.status == "fn"%}
            <a href="{% url 'editais:resultado_edital' inscricao.edital.id%}" class="btn button blue">Resultados</a>

        {%endif%}


    </div>
</div>

{% endblock %}